import type { PageServerLoad } from './$types';
import fs from 'fs';
import path from 'path';
import { parsePrismaSchema } from '$lib/utils';
// The function should be named `load` and exported.
// The type `PageServerLoad` is generated by SvelteKit's type system ($types).
export const load: PageServerLoad = async () => {
	const prismaPath = path.join(process.cwd(), 'prisma', 'schema.prisma');
	const schema = fs.readFileSync(prismaPath, 'utf-8');
	const { models, enums } = parsePrismaSchema(schema);

	// const strModels = JSON.stringify({ uiModels, nuiModels, fieldStrips })
	// Return the data as an object
	// console.log(enums);
	return { models, enums };
};
