import type { PageServerLoad } from './$types';
import fs from 'fs';
import path from 'path';
import { parsePrismaSchema } from '$lib/utils';
// The function should be named `load` and exported.
// The type `PageServerLoad` is generated by SvelteKit's type system ($types).
export const load: PageServerLoad = async () => {
	const prismaPath = path.join(process.cwd(), 'prisma', 'schema.prisma');
	// console.log(prismaPath);
	const schema = fs.readFileSync(prismaPath, 'utf-8');
	// console.log(schema);
	const models = parsePrismaSchema(schema);
	// console.log(JSON.stringify(models));

	// // // Return the data as an object
	// // const strModels = JSON.stringify({ uiModels, nuiModels, fieldStrips })
	return models;
};
