import { spawn, execSync } from 'child_process';
import type { PageServerLoad } from './$types';

function runCommandStream(
	command: string,
	args: string[],
	options: {
		cwd?: string;
		onStdout?: (data: string) => void;
		onStderr?: (data: string) => void;
		terminal?: vscode.Terminal;
	} = {}
): Promise<number> {
	return new Promise((resolve, reject) => {
		const proc = spawn(command, args, {
			cwd: options.cwd,
			shell: true,
		});

		proc.stdout.on('data', (data: any) => {
			const text = data.toString();
			options.onStdout?.(text);

			if (options.terminal) {
				options.terminal.sendText(text, false);
			}
		});

		proc.stderr.on('data', (data) => {
			const text = data.toString();
			options.onStderr?.(text);

			if (options.terminal) {
				options.terminal.sendText(text, false);
			}
		});

		proc.on('close', (code: any) => {
			resolve(code ?? 0);
		});

		proc.on('error', (err: string) => {
			reject(err);
		});
	});
}
async function run() {
	const result = await runCommandStream('ls', ['-R'], { cwd: '/home/mili/Extensions/' });
	console.log('result', result);
	console.log('ls -r', await runCommandStream('ls', ['-R']));
	console.log('ld dodo', await runCommandStream('ls', ['dodo']));
}
// The function should be named `load` and exported.
// The type `PageServerLoad` is generated by SvelteKit's type system ($types).
export const load: PageServerLoad = async () => {
	run();
};
