import type { PageServerLoad } from './$types';
import fs from 'fs';
import path from 'path';
import { parsePrismaSchema } from './parse-prisma-schema';
// The function should be named `load` and exported.
// The type `PageServerLoad` is generated by SvelteKit's type system ($types).
export const load: PageServerLoad = async () => {
	const schema = fs.readFileSync(path.join(process.cwd(), 'prisma', 'schema.prisma'), 'utf-8');
	const models = parsePrismaSchema(schema);
	// console.log(JSON.stringify(models))

	// // Return the data as an object
	// const strModels = JSON.stringify({ uiModels, nuiModels, fieldStrips })
	return {
		models,
	};
};
